<?php

return [
    'account_codes' => [
        'cash'                          => '1001',
        'bank'                          => '1002',
        'accounts_receivable'           => '1100',
        'accounts_payable'              => '2001',
        'inventory'                     => '1200',
        'input_vat'                     => '1201',
        'fixed_assets'                  => '1300',
        'accumulated_depreciation'      => '1301',
        'revaluation_surplus'           => '3100',
        'gain_on_disposal'              => '4010',
        'depreciation_expense'          => '5010',
        'loss_on_disposal'              => '5011',
        'impairment_expense'            => '5012',
        'output_vat_payable'            => '2100',
        'withholding_tax_payable'       => '2101',
        'tax_clearing'                  => '2102',
        'merchandise_sales'             => '4003',
        'inventory_adjustment_income'   => '4005',
        'expense'                       => '5006',
        'cogs'                          => '5007',
        'inventory_adjustment_expense'  => '5008',
        'inventory_wastage'             => '5009',
        'fx_gain'                       => '4900',
        'unrealized_fx_gain'            => '4901',
        'fx_loss'                       => '5900',
        'unrealized_fx_loss'            => '5901',
        'tuition_income'                => '4001',
        'admission_income'              => '4002',
        'registration_exam_certificate_income' => '4004',
        'default_revenue'               => '4000',
        'default_expense'               => '5000',
    ],
    'payment_methods' => [
        'cash'       => ['label' => 'Cash', 'type' => 'cash', 'is_bank_like' => false],
        'bank'       => ['label' => 'Bank Transfer', 'type' => 'bank', 'is_bank_like' => true],
        'cheque'     => ['label' => 'Cheque', 'type' => 'bank', 'is_bank_like' => true],
        'card'       => ['label' => 'Card', 'type' => 'digital', 'is_bank_like' => false],
        'online'     => ['label' => 'Online Payment', 'type' => 'digital', 'is_bank_like' => false],
        'bkash'      => ['label' => 'bKash', 'type' => 'mobile_wallet', 'is_bank_like' => true, 'country' => 'BD'],
        'nagad'      => ['label' => 'Nagad', 'type' => 'mobile_wallet', 'is_bank_like' => true, 'country' => 'BD'],
        'rocket'     => ['label' => 'Rocket', 'type' => 'mobile_wallet', 'is_bank_like' => true, 'country' => 'BD'],
    ],
    'default_currency' => env('ACCOUNTING_DEFAULT_CURRENCY', 'BDT'),
    'fiscal_year_start_month' => env('ACCOUNTING_FY_START_MONTH', 1),
    'period_lock_enabled' => true,
    'snapshot_on_period_close' => true,
];