<?php

/**
 * Single source of truth for industries and sub-industries.
 *
 * - "global" holds the platform-wide industry list (slug => label) and the
 *   default sub-industries (industry => slug => label) used when no country
 *   is selected, or when the selected country has no entry below.
 * - Every other top-level key is a country name (matching config/countries.php
 *   and institutes.country). A country entry lists only the industries that
 *   exist there; each value is that industry's sub-industries in the country
 *   (slug => label). An industry listed without sub-industries is written as
 *   an empty array.
 *
 * A country with no entry falls back to the "global" industry list and offers
 * no country-scoped sub-industries, so onboarding and validation never
 * dead-end. Add country entries here as they are defined; the onboarding
 * dropdowns, dashboard filters and validation pick them up automatically.
 */
return [
    'global' => [
        'industries' => [
            'education' => 'Education',
            'training_center' => 'Training Center',
            'healthcare' => 'Healthcare',
            'information_technology' => 'Information Technology',
            'finance' => 'Finance & Banking',
            'retail' => 'Retail',
            'manufacturing' => 'Manufacturing',
            'real_estate' => 'Real Estate',
            'transportation' => 'Transportation',
            // legacy alias kept for migration compatibility; canonical is transportation
            'transport' => 'Transport & Logistics',
            'service' => 'Service',
            'restaurant' => 'Restaurant',
            'hotels' => 'Hotels',
            'personal_finance' => 'Personal Finance',
            'other' => 'Other',
        ],
        'sub_industries' => [
            'education' => [
                'school' => 'School',
                'college' => 'College',
                'polytechnic' => 'Polytechnic',
                'university' => 'University',
                'madrasha' => 'Madrasha',
                // legacy academic variants preserved as NEEDS_REVIEW (not auto-migrated)
                'primary_school' => 'Primary School',
                'secondary_high_school' => 'Secondary / High School',
                'school_college' => 'School & College',
            ],
            'training_center' => [
                'training_institute' => 'Training Institute',
                'professional_training_center' => 'Professional Training Center',
                'dance_academy' => 'Dance Academy',
                'it_training_center' => 'IT Training Center',
                'vocational_training_center' => 'Vocational Training Center',
                // legacy professional variants preserved as aliases for audit trail
                'institution' => 'Institution',
                'professional_training_academy' => 'Professional Training Academy',
                'computer_it_training_institute' => 'Computer / IT Training Institute',
                'vocational_institute' => 'Vocational Institute',
                'technical_training_center' => 'Technical Training Center',
                'skill_development_center' => 'Skill Development Center',
                'martial_arts' => 'Martial Arts',
                'music_academy' => 'Music Academy',
                'sports_academy' => 'Sports Academy',
                'language_academy' => 'Language Academy',
                'coaching_centre' => 'Coaching Centre',
            ],
        ],
    ],

    'Bangladesh' => [
        'education' => [
            'school' => 'School',
            'college' => 'College',
            'polytechnic' => 'Polytechnic',
            'university' => 'University',
            'madrasha' => 'Madrasha',
            'primary_school' => 'Primary School',
            'secondary_high_school' => 'Secondary / High School',
            'school_college' => 'School & College',
        ],
        'training_center' => [
            'training_institute' => 'Training Institute',
            'professional_training_center' => 'Professional Training Center',
            'dance_academy' => 'Dance Academy',
            'it_training_center' => 'IT Training Center',
            'vocational_training_center' => 'Vocational Training Center',
            'institution' => 'Institution',
            'professional_training_academy' => 'Professional Training Academy',
            'computer_it_training_institute' => 'Computer / IT Training Institute',
            'vocational_institute' => 'Vocational Institute',
            'technical_training_center' => 'Technical Training Center',
            'skill_development_center' => 'Skill Development Center',
            'martial_arts' => 'Martial Arts',
            'music_academy' => 'Music Academy',
            'sports_academy' => 'Sports Academy',
            'language_academy' => 'Language Academy',
            'coaching_centre' => 'Coaching Centre',
        ],
        'healthcare' => [
            'hospital' => 'Hospital',
            'clinic' => 'Clinic',
            'pharmacy' => 'Pharmacy',
            'diagnostic_center' => 'Diagnostic Center',
            'nursing_home' => 'Nursing Home',
        ],
        'information_technology' => [
            'software_company' => 'Software Company',
            'it_services' => 'IT Services',
            'digital_agency' => 'Digital Agency',
        ],
        'finance' => [
            'bank' => 'Bank',
            'microfinance' => 'Microfinance',
            'insurance' => 'Insurance',
        ],
        'retail' => [
            'general_store' => 'General Store',
            'supermarket' => 'Supermarket',
            'electronics' => 'Electronics Store',
        ],
        'manufacturing' => [
            'garments' => 'Garments',
            'food_processing' => 'Food Processing',
            'pharmaceutical' => 'Pharmaceutical',
        ],
        'real_estate' => [],
        'transportation' => [],
        'transport' => [],
        'service' => [],
        'restaurant' => [],
        'hotels' => [],
        'personal_finance' => [],
        'other' => [],
    ],

    'United States' => [
        'education' => [
            'school' => 'School',
            'college' => 'College',
            'polytechnic' => 'Polytechnic',
            'university' => 'University',
            'primary_school' => 'Primary School',
            'secondary_high_school' => 'Secondary / High School',
            'school_college' => 'School & College',
        ],
        // US does not include 'madrasha' as it is a Bangladesh-specific sub-industry.
        'training_center' => [
            'training_institute' => 'Training Institute',
            'professional_training_center' => 'Professional Training Center',
            'dance_academy' => 'Dance Academy',
            'it_training_center' => 'IT Training Center',
            'vocational_training_center' => 'Vocational Training Center',
            'institution' => 'Institution',
            'professional_training_academy' => 'Professional Training Academy',
            'computer_it_training_institute' => 'Computer / IT Training Institute',
            'vocational_institute' => 'Vocational Institute',
            'technical_training_center' => 'Technical Training Center',
            'skill_development_center' => 'Skill Development Center',
            'martial_arts' => 'Martial Arts',
            'music_academy' => 'Music Academy',
            'sports_academy' => 'Sports Academy',
            'language_academy' => 'Language Academy',
            'coaching_centre' => 'Coaching Centre',
        ],
        'healthcare' => [
            'hospital' => 'Hospital',
            'clinic' => 'Clinic',
            'pharmacy' => 'Pharmacy',
        ],
        'information_technology' => [
            'software_company' => 'Software Company',
            'it_services' => 'IT Services',
            'digital_agency' => 'Digital Agency',
        ],
        'finance' => [
            'bank' => 'Bank',
            'insurance' => 'Insurance',
        ],
        'retail' => [],
        'manufacturing' => [],
        'real_estate' => [],
        'transportation' => [],
        'transport' => [],
        'service' => [],
        'restaurant' => [],
        'hotels' => [],
        'personal_finance' => [],
        'other' => [],
    ],

    /**
     * Per-industry inventory capability defaults (STEP 16).
     *
     * These are the DEFAULT capabilities for an industry. A tenant can override
     * any capability at runtime through the existing accounting-settings
     * mechanism (settings key `inventory.capability.<name>` scoped to
     * institute+branch, managed by InventoryCapabilityService). Do not put
     * industry-specific accounting logic here — capabilities only enable/disable
     * generic engine features. Industries without an entry default to a fully
     * disabled inventory (services and similar tenants keep inventory optional).
     */
    'capabilities' => [
        'education' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => false,
                'assets.revaluation' => false,
                'assets.qr' => true,
                'assets.warranty' => true,
            ],
        ],
        'retail' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => false,
                'assets.revaluation' => false,
                'assets.qr' => true,
                'assets.warranty' => true,
            ],
            'inventory.enabled' => true,
            'inventory.multi_warehouse' => true,
            'inventory.batch_tracking' => false,
            'inventory.expiry_tracking' => false,
            'inventory.serial_tracking' => false,
            'inventory.barcode' => true,
            'inventory.stock_transfer' => true,
            'inventory.stock_adjustment' => true,
            'inventory.stock_count' => true,
            'inventory.purchase_receipt' => true,
            'inventory.sales_issue' => true,
            'inventory.stock_return' => true,
            'inventory.wastage' => false,
            'inventory.bom' => false,
            'inventory.recipe' => false,
            'inventory.lot_tracking' => false,
            'inventory.consumption' => false,
            'inventory.production' => false,
        ],
        'healthcare' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => true,
                'assets.revaluation' => false,
                'assets.qr' => true,
                'assets.warranty' => true,
            ],
            'inventory.enabled' => true,
            'inventory.multi_warehouse' => true,
            'inventory.batch_tracking' => true,
            'inventory.expiry_tracking' => true,
            'inventory.serial_tracking' => true,
            'inventory.barcode' => true,
            'inventory.stock_transfer' => true,
            'inventory.stock_adjustment' => true,
            'inventory.stock_count' => true,
            'inventory.purchase_receipt' => true,
            'inventory.sales_issue' => true,
            'inventory.stock_return' => true,
            'inventory.wastage' => true,
            'inventory.bom' => false,
            'inventory.recipe' => false,
            'inventory.lot_tracking' => true,
            'inventory.consumption' => false,
            'inventory.production' => false,
        ],
        'manufacturing' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => true,
                'assets.revaluation' => false,
                'assets.qr' => true,
                'assets.warranty' => true,
            ],
            'inventory.enabled' => true,
            'inventory.multi_warehouse' => true,
            'inventory.batch_tracking' => true,
            'inventory.expiry_tracking' => true,
            'inventory.serial_tracking' => true,
            'inventory.barcode' => true,
            'inventory.stock_transfer' => true,
            'inventory.stock_adjustment' => true,
            'inventory.stock_count' => true,
            'inventory.purchase_receipt' => true,
            'inventory.sales_issue' => true,
            'inventory.stock_return' => true,
            'inventory.wastage' => true,
            'inventory.bom' => true,
            'inventory.recipe' => false,
            'inventory.lot_tracking' => true,
            'inventory.consumption' => true,
            'inventory.production' => true,
        ],
        'real_estate' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => true,
                'assets.revaluation' => true,
                'assets.qr' => true,
                'assets.warranty' => false,
            ],
            'inventory.enabled' => true,
            'inventory.multi_warehouse' => true,
            'inventory.batch_tracking' => false,
            'inventory.expiry_tracking' => false,
            'inventory.serial_tracking' => false,
            'inventory.barcode' => true,
            'inventory.stock_transfer' => true,
            'inventory.stock_adjustment' => true,
            'inventory.stock_count' => true,
            'inventory.purchase_receipt' => true,
            'inventory.sales_issue' => true,
            'inventory.stock_return' => true,
            'inventory.wastage' => false,
            'inventory.bom' => false,
            'inventory.recipe' => false,
            'inventory.lot_tracking' => false,
            'inventory.consumption' => true,
            'inventory.production' => false,
        ],
        'restaurant' => [
            'assets' => [
                'assets.enabled' => true,
                'assets.depreciation' => true,
                'assets.transfer' => true,
                'assets.disposal' => true,
                'assets.impairment' => false,
                'assets.revaluation' => false,
                'assets.qr' => true,
                'assets.warranty' => true,
            ],
            'inventory.enabled' => true,
            'inventory.multi_warehouse' => true,
            'inventory.batch_tracking' => false,
            'inventory.expiry_tracking' => true,
            'inventory.serial_tracking' => false,
            'inventory.barcode' => true,
            'inventory.stock_transfer' => true,
            'inventory.stock_adjustment' => true,
            'inventory.stock_count' => true,
            'inventory.purchase_receipt' => true,
            'inventory.sales_issue' => true,
            'inventory.stock_return' => true,
            'inventory.wastage' => true,
            'inventory.bom' => false,
            'inventory.recipe' => true,
            'inventory.lot_tracking' => false,
            'inventory.consumption' => true,
            'inventory.production' => false,
        ],
    ],
];
