@extends('layouts.institute')
@section('title','Customer Statement — AccumenAI')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Customer Statement — {{ $customer->name }}</h4><div class="d-flex gap-2"><a href="{{ request()->fullUrlWithQuery(['export'=>'csv']) }}" class="btn btn-sm btn-outline-success rounded-pill"><i class="bi bi-download"></i> CSV</a><button class="btn btn-sm btn-outline-primary rounded-pill" onclick="window.print()"><i class="bi bi-printer"></i> Print</button><a href="{{ route('sales.reports.statement') }}" class="btn btn-sm btn-outline-secondary rounded-pill">Change Customer</a><a href="{{ route('sales.reports.dashboard') }}" class="btn btn-sm btn-outline-secondary rounded-pill">Dashboard</a></div></div>
<form method="GET" class="card mb-3"><div class="card-body d-flex flex-wrap gap-2 align-items-end">
<input type="hidden" name="customer_id" value="{{ $customer->id }}">
<div><label class="form-label small mb-1">From</label><input type="date" name="from" value="{{ $filters['from'] }}" class="form-control form-control-sm"></div>
<div><label class="form-label small mb-1">To</label><input type="date" name="to" value="{{ $filters['to'] }}" class="form-control form-control-sm"></div>
<button class="btn btn-sm btn-primary rounded-pill">Filter</button><a href="{{ route('sales.reports.statement',['customer_id'=>$customer->id]) }}" class="btn btn-sm btn-outline-secondary rounded-pill">Reset</a>
</div></form>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card text-center"><div class="card-body"><small class="text-muted">Opening Balance</small><div class="fw-bold">{{ number_format($data['opening'],2) }}</div></div></div></div><div class="col-md-4"><div class="card text-center"><div class="card-body"><small class="text-muted">Closing Balance (Receivable)</small><div class="fw-bold text-primary">{{ number_format($data['closing'],2) }}</div></div></div></div><div class="col-md-4"><div class="card text-center"><div class="card-body"><small class="text-muted">Customer</small><div class="fw-semibold">{{ $customer->name }} <small class="text-muted">#{{ $customer->id }}</small></div><small class="text-muted">{{ $customer->phone }}</small></div></div></div></div>
<div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th class="text-end">Debit (Invoice)</th><th class="text-end">Credit (Payment/Credit)</th><th class="text-end">Balance</th></tr></thead><tbody>
<tr class="table-light"><td colspan="5" class="text-end fw-semibold">Opening Balance</td><td class="text-end fw-bold">{{ number_format($data['opening'],2) }}</td></tr>
@forelse($data['entries'] as $e)<tr><td>{{ $e['date'] instanceof \Carbon\Carbon ? $e['date']->format('Y-m-d') : $e['date'] }}</td><td><span class="badge bg-{{ ['invoice'=>'warning','payment'=>'success','credit_note'=>'danger','refund'=>'info'][$e['type']] ?? 'secondary' }}">{{ ucfirst(str_replace('_',' ',$e['type'])) }}</span></td><td>{{ $e['ref'] }}</td><td class="text-end">{{ $e['debit']? number_format($e['debit'],2):'—' }}</td><td class="text-end">{{ $e['credit']? number_format($e['credit'],2):'—' }}</td><td class="text-end fw-semibold">{{ number_format($e['balance'],2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-3">No transactions in range.</td></tr>@endforelse
<tr class="table-light"><td colspan="5" class="text-end fw-semibold">Closing Balance</td><td class="text-end fw-bold text-primary">{{ number_format($data['closing'],2) }}</td></tr>
</tbody></table></div></div>
<div class="card mt-3"><div class="card-body small text-muted">Source of truth: posted invoices (<code>invoices.payable</code>), payments (<code>payments.amount</code>), returns (<code>sales_returns.grand_total</code>). Running balance = Opening + Debit − Credit. Matches Finance AR derived from journals.</div></div>
@endsection
